---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - brgo.jdvgh.com
  resources:
  - synctargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - brgo.jdvgh.com
  resources:
  - synctargets/finalizers
  verbs:
  - update
- apiGroups:
  - brgo.jdvgh.com
  resources:
  - synctargets/status
  verbs:
  - get
  - patch
  - update
