# permissions for end users to edit synctargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: synctarget-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: brgo-cd-crds
    app.kubernetes.io/part-of: brgo-cd-crds
    app.kubernetes.io/managed-by: kustomize
  name: synctarget-editor-role
rules:
- apiGroups:
  - brgo.jdvgh.com
  resources:
  - synctargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - brgo.jdvgh.com
  resources:
  - synctargets/status
  verbs:
  - get
